<?xml version="1.0"?>
<root xmlns:xacro="http://www.ros.org/wiki/xacro"
      xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
      xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
      xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

	<xacro:include filename="../urdf/materials.urdf.xacro"/>

	<xacro:macro name="bar" params="thickness length *origin">
		<visual>
			<xacro:insert_block name="origin"/>
			<geometry>
				<box size="${thickness} ${thickness} ${length}" />
			</geometry>
			<material name="Silver"/>
		</visual>
		<collision>
			<xacro:insert_block name="origin"/>
			<geometry>
				<box size="${thickness} ${thickness} ${length}" />
			</geometry>
		</collision>
	</xacro:macro>

	<xacro:macro name="frame" params="prefix:='' parent:=''
	   thickness:=${cal_frame_thick}
	   width:=${cal_frame_width} depth:=${cal_frame_depth} height:=${cal_frame_height}
	   tableHeight:=${cal_frame_table_height} triangle_pos:=${cal_triangle_pos}">

		<xacro:property name="mount_triangle_length" value="0.26" />
		<xacro:property name="mount_triangle_thickness" value="0.02"/>

		<link name="${prefix}frame">
			<inertial>
				<mass value="100.0" />
				<origin xyz="0 1.2 0.3" rpy="0 0 0"/>
				<inertia ixx="4.0" ixy="0" ixz="0" iyy="4.0" iyz="0" izz="4.0"/>
			</inertial>
			<!-- horizontal front bar-->
			<xacro:bar thickness="${thickness}" length="${width}">
				<origin xyz="0 ${thickness/2} ${-thickness/2}" rpy="0 ${-pi/2} 0"/>
			</xacro:bar>
			<!-- horizontal rear bar -->
			<xacro:bar thickness="${thickness}" length="${width}">
				<origin xyz="0 ${depth+thickness/2} ${-thickness/2}" rpy="0 ${-pi/2} 0"/>
			</xacro:bar>
			<!-- horizontal rear bar top -->
			<xacro:bar thickness="${thickness}" length="${width}">
				<origin xyz="0 ${depth+thickness/2} ${height+thickness/2}" rpy="0 ${-pi/2} 0"/>
			</xacro:bar>

			<!-- left front pole -->
			<xacro:bar thickness="${thickness}" length="${thickness+tableHeight}">
				<origin xyz="${-(width+thickness)/2} ${thickness/2} ${-(thickness+tableHeight)/2}"/>
			</xacro:bar>
			<!-- right front pole -->
			<xacro:bar thickness="${thickness}" length="${thickness+tableHeight}">
				<origin xyz="${+(width+thickness)/2} ${thickness/2} ${-(thickness+tableHeight)/2}"/>
			</xacro:bar>

			<!-- left rear pole -->
			<xacro:bar thickness="${thickness}" length="${height+2*thickness+tableHeight}">
				<origin xyz="${-(width+thickness)/2} ${depth+thickness/2} ${(height-tableHeight)/2}"/>
			</xacro:bar>
			<!-- right rear pole -->
			<xacro:bar thickness="${thickness}" length="${height+2*thickness+tableHeight}">
				<origin xyz="${+(width+thickness)/2} ${depth+thickness/2} ${(height-tableHeight)/2}"/>
			</xacro:bar>

			<!-- left side bottom -->
			<xacro:bar thickness="${thickness}" length="${depth}">
				<origin xyz="${-(width+thickness)/2} ${depth/2} ${-thickness/2}"
				        rpy="${-pi/2} 0 0"/>
			</xacro:bar>
			<!-- right side bottom -->
			<xacro:bar thickness="${thickness}" length="${depth}">
				<origin xyz="${+(width+thickness)/2} ${depth/2} ${-thickness/2}"
				        rpy="${-pi/2} 0 0"/>
			</xacro:bar>

			<!-- left central pole -->
			<xacro:bar thickness="${thickness}" length="${thickness+tableHeight+(height)/2}">
				<origin xyz="${-thickness} ${(depth)/2+2*thickness} ${-(2*tableHeight-height)/4-thickness/2}"/>
			</xacro:bar>

			<!-- right central pole -->
			<xacro:bar thickness="${thickness}" length="${thickness+tableHeight+(height)/2}">
				<origin xyz="${thickness} ${(depth)/2+2*thickness} ${-(2*tableHeight-height)/4-thickness/2}"/>
			</xacro:bar>



			<!-- virtual protection plane for the screens -->
			<!-- right screen -->
			<visual>
				<origin xyz="${-width/2+0.3} ${depth-thickness} ${height}"
				        rpy="0 0 0"/>
				<geometry><box size="${0.6} ${0.1} ${0.4}"/></geometry>
				<material name="Silver"/>
			</visual>
			<!-- left screen -->
			<visual>
				<origin xyz="${width/2-0.3} ${depth-thickness} ${height}"
				        rpy="0 0 0"/>
				<geometry><box size="${0.6} ${0.1} ${0.4}"/></geometry>
				<material name="Silver"/>
			</visual>

			<collision>
				<origin xyz="0 ${depth-2*thickness} ${height/2}"
				        rpy="0 0 0"/>
				<geometry><box size="${width+2*thickness} ${0.01} ${height+0.4+2*thickness}"/></geometry>
			</collision>

			<!-- kuka mount triangle -->

			<xacro:macro name="plate" params="thickness:=${mount_triangle_thickness}
			                     length:=${mount_triangle_length} *origin">
				<visual>
					<xacro:insert_block name="origin"/>
					<geometry><box size="${length} ${length} ${thickness}"/></geometry>
					<material name="Silver"/>
				</visual>
				<collision>
					<xacro:insert_block name="origin"/>
					<geometry><box size="${length} ${length} ${thickness - 0.005}"/></geometry>
				</collision>
			</xacro:macro>

			<xacro:property name="mtth" value="${mount_triangle_thickness}"/>
			<xacro:property name="mtlen" value="${mount_triangle_length}"/>
			<!-- left plate -->

			<xacro:plate>
				<origin xyz="${triangle_pos['leftX']-mtth/2*cos(30/180.0*pi)}
				             ${triangle_pos['Y']}
				             ${triangle_pos['Z']-mtth/2*sin(30/180.0*pi)}"
				        rpy="0 ${pi/3} 0"/>
			</xacro:plate>
			<!-- right plate -->

			<xacro:plate>
				<origin xyz="${triangle_pos['rightX']+mtth/2*cos(30/180.0*pi)}
				             ${triangle_pos['Y']}
				             ${triangle_pos['Z']-mtth/2*sin(30/180.0*pi)}"
				        rpy="0 ${-pi/3} 0"/>
			</xacro:plate>
			<!-- lower plate -->

			<xacro:plate>
				<origin xyz="0 ${triangle_pos['Y']} ${triangle_pos['Z']-sin(30/180.0*pi)*mtth-mtlen/2*sin(60/180.0*pi)-mtth/2}"
				        rpy="0 0 0"/>
			</xacro:plate>

			<!-- table plane -->
			<visual>
				<origin xyz="0 ${depth/2} -0.01"
				        rpy="0 0 0"/>
				<geometry><box size="${width} ${depth} ${0.02}"/></geometry>
				<material name="Silver"/>
			</visual>
			<collision>
				<origin xyz="0 ${depth/2} -0.01"
				        rpy="0 0 0"/>
				<geometry><box size="${width} ${depth} ${0.02}"/></geometry>
			</collision>

		</link>

		<gazebo reference="${prefix}frame">
			<material value="Gazebo/Grey"/>
		</gazebo>

		<xacro:if value="${parent != ''}">
			<joint name="${prefix}frame_joint" type="fixed">
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<parent link="${parent}"/>
				<child link="${prefix}frame"/>
			</joint>
		</xacro:if>

	</xacro:macro>

</root>
